// <auto-generated />
using System;
using Mantaras.Juridico.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mantaras.Juridico.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JuridicoDbContext))]
    [Migration("20260930125339_AgregarModeloAgenda")]
    partial class AgregarModeloAgenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.AgendaGeneracionRegla", b =>
                {
                    b.Property<long>("AgendaGeneracionReglaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AgendaGeneracionReglaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long?>("CasoOrigenId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("EntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EntradaAgendaOrigenId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpedienteOrigenId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("FechaBase")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ObservacionOrigenId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrigenFechaBase")
                        .HasColumnType("integer");

                    b.Property<long>("ReglaVencimientoId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("UsuarioGeneracionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AgendaGeneracionReglaId");

                    b.HasIndex("CasoOrigenId");

                    b.HasIndex("ClaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("EntradaAgendaId")
                        .IsUnique();

                    b.HasIndex("EntradaAgendaOrigenId");

                    b.HasIndex("ExpedienteOrigenId");

                    b.HasIndex("ObservacionOrigenId");

                    b.HasIndex("ReglaVencimientoId");

                    b.HasIndex("UsuarioGeneracionId");

                    b.ToTable("AgendaGeneracionesReglas", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgendaGeneracionesReglas_Origen", "(\"OrigenFechaBase\" = 1 AND num_nonnulls(\"EntradaAgendaOrigenId\", \"CasoOrigenId\", \"ExpedienteOrigenId\", \"ObservacionOrigenId\") = 0) OR (\"OrigenFechaBase\" = 2 AND \"EntradaAgendaOrigenId\" IS NOT NULL AND num_nonnulls(\"CasoOrigenId\", \"ExpedienteOrigenId\", \"ObservacionOrigenId\") = 0) OR (\"OrigenFechaBase\" = 3 AND \"CasoOrigenId\" IS NOT NULL AND num_nonnulls(\"EntradaAgendaOrigenId\", \"ExpedienteOrigenId\", \"ObservacionOrigenId\") = 0) OR (\"OrigenFechaBase\" = 4 AND \"ExpedienteOrigenId\" IS NOT NULL AND num_nonnulls(\"EntradaAgendaOrigenId\", \"CasoOrigenId\", \"ObservacionOrigenId\") = 0) OR (\"OrigenFechaBase\" = 5 AND \"ObservacionOrigenId\" IS NOT NULL AND num_nonnulls(\"EntradaAgendaOrigenId\", \"CasoOrigenId\", \"ExpedienteOrigenId\") = 0)");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Caso", b =>
                {
                    b.Property<long>("CasoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CasoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("FaseInterna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroBeneficio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroExpedienteAnses")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("TipoBeneficioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TipoExpedienteAdministrativoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoTramite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CasoId");

                    b.HasIndex("FaseInterna");

                    b.HasIndex("NumeroBeneficio");

                    b.HasIndex("NumeroExpedienteAnses");

                    b.HasIndex("TipoBeneficioId");

                    b.HasIndex("TipoExpedienteAdministrativoId");

                    b.HasIndex("Titulo");

                    b.ToTable("Casos", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.CasoCliente", b =>
                {
                    b.Property<long>("CasoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoParticipacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CasoId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("CasosClientes", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.CasoExpediente", b =>
                {
                    b.Property<long>("CasoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.HasKey("CasoId", "ExpedienteId");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("CasosExpedientes", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClaveSeguridadSocial")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Cuil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DerivadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DerivadoPorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DerivadoPorTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Localidad")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Cuil")
                        .IsUnique();

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Apellido", "Nombre");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.DiaInhabil", b =>
                {
                    b.Property<long>("DiaInhabilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiaInhabilId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DiaInhabilId");

                    b.HasIndex("Activo");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("DiasInhabiles", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgenda", b =>
                {
                    b.Property<long>("EntradaAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntradaAgendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraVencimiento")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<long?>("RecurrenciaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoEntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Argentina/Buenos_Aires");

                    b.HasKey("EntradaAgendaId");

                    b.HasIndex("Activo");

                    b.HasIndex("RecurrenciaAgendaId");

                    b.HasIndex("TipoEntradaAgendaId");

                    b.HasIndex("FechaInicio", "Estado");

                    b.HasIndex("FechaVencimiento", "Estado");

                    b.ToTable("EntradasAgenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_EntradasAgenda_Fechas", "\"FechaFin\" IS NULL OR \"FechaFin\" >= \"FechaInicio\"");

                            t.HasCheckConstraint("CK_EntradasAgenda_HoraFin", "\"HoraFin\" IS NULL OR \"FechaFin\" IS NOT NULL");

                            t.HasCheckConstraint("CK_EntradasAgenda_HoraVencimiento", "\"HoraVencimiento\" IS NULL OR \"FechaVencimiento\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaCaso", b =>
                {
                    b.Property<long>("EntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<long>("CasoId")
                        .HasColumnType("bigint");

                    b.HasKey("EntradaAgendaId", "CasoId");

                    b.HasIndex("CasoId");

                    b.ToTable("EntradasAgendaCasos", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaCliente", b =>
                {
                    b.Property<long>("EntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.HasKey("EntradaAgendaId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("EntradasAgendaClientes", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaExpediente", b =>
                {
                    b.Property<long>("EntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.HasKey("EntradaAgendaId", "ExpedienteId");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("EntradasAgendaExpedientes", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaResponsable", b =>
                {
                    b.Property<long>("EntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("EntradaAgendaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EntradasAgendaResponsables", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Expediente", b =>
                {
                    b.Property<long>("ExpedienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ExpedienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Caratula")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EstadoLegal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ExpedientePadreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Juzgado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroExpediente")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoExpediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ExpedienteId");

                    b.HasIndex("ExpedientePadreId");

                    b.HasIndex("NumeroExpediente");

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.HojaResumenCaso", b =>
                {
                    b.Property<long>("CasoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HaberInicialMonto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("HaberInicialObservacion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("HaberInicialPbu")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("HaberInicialReajustadoCaracteristicas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MovilidadActualizacionAnio")
                        .HasColumnType("integer");

                    b.Property<int?>("MovilidadActualizacionMes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MovilidadMonto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MovilidadObservaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("RetroactivoFechaActualizacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RetroactivoFechaInicio")
                        .HasColumnType("date");

                    b.Property<decimal?>("RetroactivoMonto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RetroactivoObservacion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool?>("TieneCalculoPrevio")
                        .HasColumnType("boolean");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CasoId");

                    b.ToTable("HojasResumenCasos", null, t =>
                        {
                            t.HasCheckConstraint("CK_HojasResumenCasos_PeriodoMovilidad", "(\r\n    \"MovilidadActualizacionMes\" IS NULL\r\n    AND \"MovilidadActualizacionAnio\" IS NULL\r\n)\r\nOR\r\n(\r\n    \"MovilidadActualizacionMes\" IS NOT NULL\r\n    AND \"MovilidadActualizacionAnio\" IS NOT NULL\r\n    AND \"MovilidadActualizacionMes\" BETWEEN 1 AND 12\r\n    AND \"MovilidadActualizacionAnio\" BETWEEN 1 AND 9999\r\n)");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Observacion", b =>
                {
                    b.Property<long>("ObservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ObservacionId"));

                    b.Property<long?>("CasoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ObservacionId");

                    b.HasIndex("CasoId", "FechaCreacion");

                    b.HasIndex("ClienteId", "FechaCreacion");

                    b.HasIndex("ExpedienteId", "FechaCreacion");

                    b.ToTable("Observaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Observaciones_UnPropietario", "num_nonnulls(\"ClienteId\", \"CasoId\", \"ExpedienteId\") = 1");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.OpcionCatalogo", b =>
                {
                    b.Property<long>("OpcionCatalogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OpcionCatalogoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OpcionCatalogoId");

                    b.HasIndex("Tipo", "Activo");

                    b.HasIndex("Tipo", "Nombre")
                        .IsUnique();

                    b.ToTable("OpcionesCatalogo", (string)null);

                    b.HasData(
                        new
                        {
                            OpcionCatalogoId = 1L,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Preadministrativa",
                            Tipo = "fases-internas",
                            UsuarioCreacion = "Sistema"
                        },
                        new
                        {
                            OpcionCatalogoId = 2L,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juicio",
                            Tipo = "fases-internas",
                            UsuarioCreacion = "Sistema"
                        },
                        new
                        {
                            OpcionCatalogoId = 3L,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Postjuicio",
                            Tipo = "fases-internas",
                            UsuarioCreacion = "Sistema"
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecordatorioAgenda", b =>
                {
                    b.Property<long>("RecordatorioAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordatorioAgendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Atendido")
                        .HasColumnType("boolean");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<long>("EntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaAtendidoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaProgramadaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UsuarioAtendioId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RecordatorioAgendaId");

                    b.HasIndex("EntradaAgendaId");

                    b.HasIndex("UsuarioAtendioId");

                    b.HasIndex("FechaProgramadaUtc", "Atendido", "Activo");

                    b.ToTable("RecordatoriosAgenda", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecordatorioPredeterminadoReglaVencimiento", b =>
                {
                    b.Property<long>("RecordatorioPredeterminadoReglaVencimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordatorioPredeterminadoReglaVencimientoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("BaseCalculo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinutosAnticipacion")
                        .HasColumnType("integer");

                    b.Property<long>("ReglaVencimientoId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RecordatorioPredeterminadoReglaVencimientoId");

                    b.HasIndex("ReglaVencimientoId", "BaseCalculo", "MinutosAnticipacion")
                        .IsUnique();

                    b.ToTable("RecordatoriosPredeterminadosReglasVencimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecordatoriosPredeterminadosReglasVencimiento_Anticipacion", "\"MinutosAnticipacion\" >= 0");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecordatorioPredeterminadoTipoAgenda", b =>
                {
                    b.Property<long>("RecordatorioPredeterminadoTipoAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordatorioPredeterminadoTipoAgendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("BaseCalculo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinutosAnticipacion")
                        .HasColumnType("integer");

                    b.Property<long>("TipoEntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RecordatorioPredeterminadoTipoAgendaId");

                    b.HasIndex("TipoEntradaAgendaId", "BaseCalculo", "MinutosAnticipacion")
                        .IsUnique();

                    b.ToTable("RecordatoriosPredeterminadosTiposAgenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecordatoriosPredeterminadosTiposAgenda_Anticipacion", "\"MinutosAnticipacion\" >= 0");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecurrenciaAgenda", b =>
                {
                    b.Property<long>("RecurrenciaAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecurrenciaAgendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("DiaMes")
                        .HasColumnType("integer");

                    b.Property<int?>("DiasSemana")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("integer");

                    b.Property<int>("Intervalo")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximoOcurrencias")
                        .HasColumnType("integer");

                    b.Property<int?>("MesAnio")
                        .HasColumnType("integer");

                    b.Property<int>("OcurrenciasGeneradas")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ProximaFecha")
                        .HasColumnType("date");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Argentina/Buenos_Aires");

                    b.HasKey("RecurrenciaAgendaId");

                    b.HasIndex("ProximaFecha", "Activo");

                    b.ToTable("RecurrenciasAgenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurrenciasAgenda_DiaMes", "\"DiaMes\" IS NULL OR (\"DiaMes\" BETWEEN 1 AND 31)");

                            t.HasCheckConstraint("CK_RecurrenciasAgenda_DiasSemana", "\"DiasSemana\" IS NULL OR (\"DiasSemana\" BETWEEN 1 AND 127)");

                            t.HasCheckConstraint("CK_RecurrenciasAgenda_Fechas", "\"FechaFin\" IS NULL OR \"FechaFin\" >= \"FechaInicio\"");

                            t.HasCheckConstraint("CK_RecurrenciasAgenda_Intervalo", "\"Intervalo\" > 0");

                            t.HasCheckConstraint("CK_RecurrenciasAgenda_MaximoOcurrencias", "\"MaximoOcurrencias\" IS NULL OR \"MaximoOcurrencias\" > 0");

                            t.HasCheckConstraint("CK_RecurrenciasAgenda_MesAnio", "\"MesAnio\" IS NULL OR (\"MesAnio\" BETWEEN 1 AND 12)");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.ReglaVencimiento", b =>
                {
                    b.Property<long>("ReglaVencimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReglaVencimientoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CantidadDias")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("HoraSugerida")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrioridadGenerada")
                        .HasColumnType("integer");

                    b.Property<int>("SentidoCalculo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoComputo")
                        .HasColumnType("integer");

                    b.Property<long>("TipoEntradaAgendaId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ReglaVencimientoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("TipoEntradaAgendaId", "Activo");

                    b.ToTable("ReglasVencimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReglasVencimiento_CantidadDias", "\"CantidadDias\" >= 0");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RelacionFamiliar", b =>
                {
                    b.Property<long>("RelacionFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RelacionFamiliarId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("ClienteAId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteBId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParentescoDeB")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RelacionFamiliarId");

                    b.HasIndex("ClienteBId");

                    b.HasIndex("ClienteAId", "ClienteBId")
                        .IsUnique();

                    b.ToTable("RelacionesFamiliares", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelacionesFamiliares_ClientesOrdenados", "\"ClienteAId\" < \"ClienteBId\"");

                            t.HasCheckConstraint("CK_RelacionesFamiliares_ParentescoValido", "\"ParentescoDeB\" BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.TipoBeneficio", b =>
                {
                    b.Property<long>("TipoBeneficioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TipoBeneficioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TipoBeneficioId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposBeneficio", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.TipoEntradaAgenda", b =>
                {
                    b.Property<long>("TipoEntradaAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TipoEntradaAgendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TipoEntradaAgendaId");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposEntradaAgenda", (string)null);

                    b.HasData(
                        new
                        {
                            TipoEntradaAgendaId = 1L,
                            Activo = true,
                            Color = "blue",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tarea interna",
                            UsuarioCreacion = "Sistema"
                        },
                        new
                        {
                            TipoEntradaAgendaId = 2L,
                            Activo = true,
                            Color = "red",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vencimiento procesal",
                            UsuarioCreacion = "Sistema"
                        },
                        new
                        {
                            TipoEntradaAgendaId = 3L,
                            Activo = true,
                            Color = "purple",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Audiencia o turno",
                            UsuarioCreacion = "Sistema"
                        },
                        new
                        {
                            TipoEntradaAgendaId = 4L,
                            Activo = true,
                            Color = "yellow",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Recordatorio general",
                            UsuarioCreacion = "Sistema"
                        },
                        new
                        {
                            TipoEntradaAgendaId = 5L,
                            Activo = true,
                            Color = "green",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Reunión o llamado",
                            UsuarioCreacion = "Sistema"
                        });
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.TipoExpedienteAdministrativo", b =>
                {
                    b.Property<long>("TipoExpedienteAdministrativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TipoExpedienteAdministrativoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TipoExpedienteAdministrativoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposExpedienteAdministrativo", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.AgendaGeneracionRegla", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Caso", "CasoOrigen")
                        .WithMany()
                        .HasForeignKey("CasoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgenda")
                        .WithOne("GeneracionRegla")
                        .HasForeignKey("Mantaras.Juridico.Domain.Entities.AgendaGeneracionRegla", "EntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgendaOrigen")
                        .WithMany("GeneracionesDependientes")
                        .HasForeignKey("EntradaAgendaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Expediente", "ExpedienteOrigen")
                        .WithMany()
                        .HasForeignKey("ExpedienteOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Observacion", "ObservacionOrigen")
                        .WithMany()
                        .HasForeignKey("ObservacionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.ReglaVencimiento", "ReglaVencimiento")
                        .WithMany("Generaciones")
                        .HasForeignKey("ReglaVencimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UsuarioGeneracionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CasoOrigen");

                    b.Navigation("EntradaAgenda");

                    b.Navigation("EntradaAgendaOrigen");

                    b.Navigation("ExpedienteOrigen");

                    b.Navigation("ObservacionOrigen");

                    b.Navigation("ReglaVencimiento");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Caso", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.TipoBeneficio", "TipoBeneficio")
                        .WithMany("Casos")
                        .HasForeignKey("TipoBeneficioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.TipoExpedienteAdministrativo", "TipoExpedienteAdministrativo")
                        .WithMany("Casos")
                        .HasForeignKey("TipoExpedienteAdministrativoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoBeneficio");

                    b.Navigation("TipoExpedienteAdministrativo");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.CasoCliente", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Caso", "Caso")
                        .WithMany("Clientes")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Casos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.CasoExpediente", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Caso", "Caso")
                        .WithMany("Expedientes")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Expediente", "Expediente")
                        .WithMany("Casos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgenda", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.RecurrenciaAgenda", "Recurrencia")
                        .WithMany("Entradas")
                        .HasForeignKey("RecurrenciaAgendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.TipoEntradaAgenda", "TipoEntrada")
                        .WithMany("Entradas")
                        .HasForeignKey("TipoEntradaAgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recurrencia");

                    b.Navigation("TipoEntrada");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaCaso", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Caso", "Caso")
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgenda")
                        .WithMany("Casos")
                        .HasForeignKey("EntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("EntradaAgenda");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaCliente", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgenda")
                        .WithMany("Clientes")
                        .HasForeignKey("EntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EntradaAgenda");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaExpediente", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgenda")
                        .WithMany("Expedientes")
                        .HasForeignKey("EntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntradaAgenda");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgendaResponsable", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgenda")
                        .WithMany("Responsables")
                        .HasForeignKey("EntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntradaAgenda");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Expediente", "ExpedientePadre")
                        .WithMany("ExpedientesDerivados")
                        .HasForeignKey("ExpedientePadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExpedientePadre");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.HojaResumenCaso", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Caso", "Caso")
                        .WithOne("HojaResumen")
                        .HasForeignKey("Mantaras.Juridico.Domain.Entities.HojaResumenCaso", "CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Observacion", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Caso", "Caso")
                        .WithMany("HistorialObservaciones")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Cliente", "Cliente")
                        .WithMany("HistorialObservaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Expediente", "Expediente")
                        .WithMany("HistorialObservaciones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caso");

                    b.Navigation("Cliente");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecordatorioAgenda", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.EntradaAgenda", "EntradaAgenda")
                        .WithMany("Recordatorios")
                        .HasForeignKey("EntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAtendioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntradaAgenda");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecordatorioPredeterminadoReglaVencimiento", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.ReglaVencimiento", "ReglaVencimiento")
                        .WithMany("RecordatoriosPredeterminados")
                        .HasForeignKey("ReglaVencimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReglaVencimiento");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecordatorioPredeterminadoTipoAgenda", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.TipoEntradaAgenda", "TipoEntradaAgenda")
                        .WithMany("RecordatoriosPredeterminados")
                        .HasForeignKey("TipoEntradaAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEntradaAgenda");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.ReglaVencimiento", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.TipoEntradaAgenda", "TipoEntrada")
                        .WithMany("ReglasVencimiento")
                        .HasForeignKey("TipoEntradaAgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEntrada");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RelacionFamiliar", b =>
                {
                    b.HasOne("Mantaras.Juridico.Domain.Entities.Cliente", "ClienteA")
                        .WithMany("RelacionesFamiliaresComoA")
                        .HasForeignKey("ClienteAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Domain.Entities.Cliente", "ClienteB")
                        .WithMany("RelacionesFamiliaresComoB")
                        .HasForeignKey("ClienteBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteA");

                    b.Navigation("ClienteB");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Mantaras.Juridico.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Caso", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Expedientes");

                    b.Navigation("HistorialObservaciones");

                    b.Navigation("HojaResumen");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("HistorialObservaciones");

                    b.Navigation("RelacionesFamiliaresComoA");

                    b.Navigation("RelacionesFamiliaresComoB");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.EntradaAgenda", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("Clientes");

                    b.Navigation("Expedientes");

                    b.Navigation("GeneracionRegla");

                    b.Navigation("GeneracionesDependientes");

                    b.Navigation("Recordatorios");

                    b.Navigation("Responsables");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.Expediente", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("ExpedientesDerivados");

                    b.Navigation("HistorialObservaciones");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.RecurrenciaAgenda", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.ReglaVencimiento", b =>
                {
                    b.Navigation("Generaciones");

                    b.Navigation("RecordatoriosPredeterminados");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.TipoBeneficio", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.TipoEntradaAgenda", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("RecordatoriosPredeterminados");

                    b.Navigation("ReglasVencimiento");
                });

            modelBuilder.Entity("Mantaras.Juridico.Domain.Entities.TipoExpedienteAdministrativo", b =>
                {
                    b.Navigation("Casos");
                });
#pragma warning restore 612, 618
        }
    }
}
